version: '2'
services:
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb3
        ports:
        - 27017:27017
        volumes:
        - .:/data/db
    flask-service:
        build:
            context: .
        restart: always
        container_name: flask
        depends_on:
            - mongodb
        ports:
            - 5000:5000
        environment:
            - "MONGO_HOSTNAME=mongodb"